import type {
  User, Organization, Customer, Lead, Invoice, Payment, Product, Warehouse,
  StockMovement, Vendor, PurchaseOrder, Expense, ExpenseCategory, Budget,
  Subscription, ReimbursementClaim, Employee, LeaveRequest, Attendance,
  PayrollRun, Project, Task, Server, ServiceApp, Incident, MaintenanceWindow,
  AlertRule, Notification, AuditLog, Account, Transaction
} from '@/types';

// Helper to generate IDs
const generateId = () => Math.random().toString(36).substr(2, 9);

// Demo Organization
export const demoOrganization: Organization = {
  id: 'org-1',
  name: 'Acme Corporation',
  logo: undefined,
  address: '123 Business Ave, Suite 100, San Francisco, CA 94102',
  currency: 'USD',
  fiscalYearStart: '01-01',
  createdAt: '2024-01-01T00:00:00Z',
};

// Demo Users
export const demoUsers: User[] = [
  {
    id: 'user-1',
    email: 'admin@acme.com',
    name: 'Alex Johnson',
    role: 'owner',
    organizationId: 'org-1',
    createdAt: '2024-01-01T00:00:00Z',
    lastLogin: '2025-02-09T10:00:00Z',
    status: 'active',
  },
  {
    id: 'user-2',
    email: 'finance@acme.com',
    name: 'Sarah Chen',
    role: 'finance',
    organizationId: 'org-1',
    createdAt: '2024-01-15T00:00:00Z',
    lastLogin: '2025-02-08T14:30:00Z',
    status: 'active',
  },
  {
    id: 'user-3',
    email: 'devops@acme.com',
    name: 'Mike Thompson',
    role: 'devops',
    organizationId: 'org-1',
    createdAt: '2024-02-01T00:00:00Z',
    lastLogin: '2025-02-09T09:15:00Z',
    status: 'active',
  },
  {
    id: 'user-4',
    email: 'sales@acme.com',
    name: 'Emily Davis',
    role: 'sales',
    organizationId: 'org-1',
    createdAt: '2024-02-10T00:00:00Z',
    lastLogin: '2025-02-07T16:45:00Z',
    status: 'active',
  },
];

// Demo Customers
export const demoCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'TechStart Inc.',
    email: 'billing@techstart.io',
    phone: '+1 555-0101',
    company: 'TechStart Inc.',
    address: '456 Innovation Blvd, Austin, TX 78701',
    status: 'active',
    createdAt: '2024-03-01T00:00:00Z',
    totalSpent: 45000,
  },
  {
    id: 'cust-2',
    name: 'Global Retail Co.',
    email: 'accounts@globalretail.com',
    phone: '+1 555-0102',
    company: 'Global Retail Co.',
    address: '789 Commerce St, New York, NY 10001',
    status: 'active',
    createdAt: '2024-03-15T00:00:00Z',
    totalSpent: 125000,
  },
  {
    id: 'cust-3',
    name: 'HealthPlus Medical',
    email: 'procurement@healthplus.org',
    phone: '+1 555-0103',
    company: 'HealthPlus Medical',
    address: '321 Medical Center Dr, Boston, MA 02101',
    status: 'active',
    createdAt: '2024-04-01T00:00:00Z',
    totalSpent: 78500,
  },
];

// Demo Leads
export const demoLeads: Lead[] = [
  {
    id: 'lead-1',
    name: 'James Wilson',
    email: 'james@startup.co',
    company: 'NextGen Startup',
    phone: '+1 555-0201',
    status: 'new',
    value: 25000,
    source: 'Website',
    assignedTo: 'user-4',
    createdAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'lead-2',
    name: 'Lisa Anderson',
    email: 'lisa@enterprise.com',
    company: 'Enterprise Solutions',
    phone: '+1 555-0202',
    status: 'contacted',
    value: 75000,
    source: 'Referral',
    assignedTo: 'user-4',
    createdAt: '2025-01-28T00:00:00Z',
  },
  {
    id: 'lead-3',
    name: 'Robert Martinez',
    email: 'robert@bigco.com',
    company: 'BigCo Industries',
    status: 'proposal',
    value: 150000,
    source: 'LinkedIn',
    assignedTo: 'user-4',
    createdAt: '2025-01-20T00:00:00Z',
  },
];

// Demo Invoices
export const demoInvoices: Invoice[] = [
  {
    id: 'inv-1',
    number: 'INV-2025-001',
    customerId: 'cust-1',
    customerName: 'TechStart Inc.',
    items: [
      { id: 'item-1', description: 'Software License - Annual', quantity: 5, unitPrice: 2000, tax: 200, total: 10200, productId: 'prod-1' },
      { id: 'item-2', description: 'Implementation Services', quantity: 20, unitPrice: 150, tax: 300, total: 3300 },
    ],
    subtotal: 13000,
    tax: 500,
    total: 13500,
    status: 'paid',
    dueDate: '2025-02-15',
    createdAt: '2025-01-15T00:00:00Z',
    paidAt: '2025-02-10T00:00:00Z',
  },
  {
    id: 'inv-2',
    number: 'INV-2025-002',
    customerId: 'cust-2',
    customerName: 'Global Retail Co.',
    items: [
      { id: 'item-3', description: 'Enterprise Package', quantity: 1, unitPrice: 50000, tax: 5000, total: 55000 },
    ],
    subtotal: 50000,
    tax: 5000,
    total: 55000,
    status: 'sent',
    dueDate: '2025-02-28',
    createdAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'inv-3',
    number: 'INV-2025-003',
    customerId: 'cust-3',
    customerName: 'HealthPlus Medical',
    items: [
      { id: 'item-4', description: 'Consulting Hours', quantity: 40, unitPrice: 200, tax: 800, total: 8800 },
    ],
    subtotal: 8000,
    tax: 800,
    total: 8800,
    status: 'pending',
    dueDate: '2025-03-01',
    createdAt: '2025-02-05T00:00:00Z',
  },
];

// Demo Products
export const demoProducts: Product[] = [
  {
    id: 'prod-1',
    sku: 'SW-LIC-001',
    name: 'Software License - Annual',
    description: 'Annual software license for enterprise users',
    category: 'Software',
    unit: 'license',
    purchasePrice: 800,
    sellingPrice: 2000,
    taxRate: 10,
    reorderLevel: 10,
    currentStock: 50,
    warehouseId: 'wh-1',
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'prod-2',
    sku: 'HW-SRV-001',
    name: 'Server Hardware Kit',
    description: 'Complete server hardware package',
    category: 'Hardware',
    unit: 'unit',
    purchasePrice: 5000,
    sellingPrice: 8500,
    taxRate: 10,
    reorderLevel: 5,
    currentStock: 3,
    warehouseId: 'wh-1',
    status: 'active',
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 'prod-3',
    sku: 'SVC-SUP-001',
    name: 'Premium Support Package',
    description: '24/7 premium support for 1 year',
    category: 'Services',
    unit: 'package',
    purchasePrice: 0,
    sellingPrice: 5000,
    taxRate: 10,
    reorderLevel: 0,
    currentStock: 999,
    warehouseId: 'wh-1',
    status: 'active',
    createdAt: '2024-03-01T00:00:00Z',
  },
];

// Demo Warehouses
export const demoWarehouses: Warehouse[] = [
  { id: 'wh-1', name: 'Main Warehouse', address: '100 Warehouse Rd, San Francisco, CA', isDefault: true },
  { id: 'wh-2', name: 'East Coast Store', address: '200 Storage Ave, New York, NY', isDefault: false },
];

// Demo Vendors
export const demoVendors: Vendor[] = [
  {
    id: 'vendor-1',
    name: 'Tech Supplies Co.',
    email: 'orders@techsupplies.com',
    phone: '+1 555-0301',
    address: '500 Supplier Way, Seattle, WA',
    paymentTerms: 'Net 30',
    status: 'active',
    createdAt: '2024-01-15T00:00:00Z',
    totalPurchases: 125000,
  },
  {
    id: 'vendor-2',
    name: 'Cloud Services Inc.',
    email: 'billing@cloudservices.io',
    phone: '+1 555-0302',
    status: 'active',
    createdAt: '2024-02-01T00:00:00Z',
    totalPurchases: 48000,
  },
];

// Demo Expense Categories
export const demoExpenseCategories: ExpenseCategory[] = [
  { id: 'expcat-1', name: 'Travel', color: '#3B82F6', description: 'Business travel expenses' },
  { id: 'expcat-2', name: 'Office Supplies', color: '#10B981', description: 'Office equipment and supplies' },
  { id: 'expcat-3', name: 'Software', color: '#8B5CF6', description: 'Software subscriptions and licenses' },
  { id: 'expcat-4', name: 'Infrastructure', color: '#F59E0B', description: 'Server and cloud infrastructure' },
  { id: 'expcat-5', name: 'Marketing', color: '#EC4899', description: 'Marketing and advertising' },
  { id: 'expcat-6', name: 'Meals & Entertainment', color: '#14B8A6', description: 'Business meals and entertainment' },
  { id: 'expcat-7', name: 'Utilities', color: '#6366F1', description: 'Utility bills and services' },
];

// Demo Expenses
export const demoExpenses: Expense[] = [
  {
    id: 'exp-1',
    title: 'Flight to New York - Client Meeting',
    amount: 450,
    tax: 0,
    total: 450,
    category: 'Travel',
    categoryId: 'expcat-1',
    vendor: 'United Airlines',
    paymentMethod: 'card',
    paidBy: 'company',
    reimbursable: false,
    tags: ['client-meeting', 'q1'],
    status: 'paid',
    date: '2025-02-01',
    createdAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'exp-2',
    title: 'AWS Monthly Bill - January',
    amount: 2340,
    tax: 234,
    total: 2574,
    category: 'Infrastructure',
    categoryId: 'expcat-4',
    vendor: 'Amazon Web Services',
    vendorId: 'vendor-2',
    paymentMethod: 'card',
    paidBy: 'company',
    reimbursable: false,
    tags: ['infrastructure', 'aws'],
    status: 'paid',
    date: '2025-01-31',
    createdAt: '2025-01-31T00:00:00Z',
  },
  {
    id: 'exp-3',
    title: 'Team Lunch - Project Celebration',
    amount: 185,
    tax: 18.5,
    total: 203.5,
    category: 'Meals & Entertainment',
    categoryId: 'expcat-6',
    vendor: 'The Local Bistro',
    paymentMethod: 'card',
    paidBy: 'employee',
    employeeId: 'emp-1',
    employeeName: 'Alex Johnson',
    reimbursable: true,
    tags: ['team-event'],
    status: 'submitted',
    date: '2025-02-05',
    createdAt: '2025-02-05T00:00:00Z',
  },
  {
    id: 'exp-4',
    title: 'Figma Annual Subscription',
    amount: 144,
    tax: 0,
    total: 144,
    category: 'Software',
    categoryId: 'expcat-3',
    vendor: 'Figma Inc.',
    paymentMethod: 'card',
    paidBy: 'company',
    reimbursable: false,
    tags: ['software', 'design'],
    status: 'paid',
    date: '2025-01-15',
    createdAt: '2025-01-15T00:00:00Z',
  },
];

// Demo Subscriptions
export const demoSubscriptions: Subscription[] = [
  {
    id: 'sub-1',
    vendor: 'Slack Technologies',
    plan: 'Business+',
    billingCycle: 'monthly',
    amount: 150,
    currency: 'USD',
    nextRenewal: '2025-03-01',
    status: 'active',
    owner: 'Alex Johnson',
    ownerId: 'user-1',
    paymentMethod: 'Company Card',
    categoryId: 'expcat-3',
    createdAt: '2024-03-01T00:00:00Z',
  },
  {
    id: 'sub-2',
    vendor: 'GitHub',
    plan: 'Team',
    billingCycle: 'yearly',
    amount: 480,
    currency: 'USD',
    nextRenewal: '2025-06-15',
    status: 'active',
    owner: 'Mike Thompson',
    ownerId: 'user-3',
    paymentMethod: 'Company Card',
    categoryId: 'expcat-3',
    createdAt: '2024-06-15T00:00:00Z',
  },
  {
    id: 'sub-3',
    vendor: 'AWS',
    plan: 'Pay-as-you-go',
    billingCycle: 'monthly',
    amount: 2500,
    currency: 'USD',
    nextRenewal: '2025-03-01',
    status: 'active',
    owner: 'Mike Thompson',
    ownerId: 'user-3',
    paymentMethod: 'Company Card',
    categoryId: 'expcat-4',
    createdAt: '2024-01-01T00:00:00Z',
  },
];

// Demo Budgets
export const demoBudgets: Budget[] = [
  {
    id: 'budget-1',
    categoryId: 'expcat-1',
    categoryName: 'Travel',
    amount: 5000,
    period: 'monthly',
    spent: 1850,
    alertThreshold: 80,
    startDate: '2025-02-01',
    endDate: '2025-02-28',
  },
  {
    id: 'budget-2',
    categoryId: 'expcat-4',
    categoryName: 'Infrastructure',
    amount: 10000,
    period: 'monthly',
    spent: 7500,
    alertThreshold: 80,
    startDate: '2025-02-01',
    endDate: '2025-02-28',
  },
];

// Demo Employees
export const demoEmployees: Employee[] = [
  {
    id: 'emp-1',
    employeeId: 'EMP-001',
    userId: 'user-1',
    name: 'Alex Johnson',
    email: 'admin@acme.com',
    phone: '+1 555-0001',
    department: 'Executive',
    position: 'CEO',
    joinDate: '2024-01-01',
    salary: 180000,
    status: 'active',
  },
  {
    id: 'emp-2',
    employeeId: 'EMP-002',
    userId: 'user-2',
    name: 'Sarah Chen',
    email: 'finance@acme.com',
    phone: '+1 555-0002',
    department: 'Finance',
    position: 'CFO',
    manager: 'emp-1',
    joinDate: '2024-01-15',
    salary: 150000,
    status: 'active',
  },
  {
    id: 'emp-3',
    employeeId: 'EMP-003',
    userId: 'user-3',
    name: 'Mike Thompson',
    email: 'devops@acme.com',
    phone: '+1 555-0003',
    department: 'Engineering',
    position: 'DevOps Lead',
    manager: 'emp-1',
    joinDate: '2024-02-01',
    salary: 130000,
    status: 'active',
  },
];

// Demo Servers
export const demoServers: Server[] = [
  {
    id: 'srv-1',
    name: 'prod-api-01',
    provider: 'aws',
    region: 'us-east-1',
    environment: 'production',
    publicIp: '54.***.***.123',
    hostname: 'api.acme.com',
    os: 'Ubuntu 22.04 LTS',
    cpu: '4 vCPU',
    ram: '16 GB',
    disk: '100 GB SSD',
    sshPort: 22,
    firewallEnabled: true,
    monitoringEnabled: true,
    monthlyCost: 150,
    currency: 'USD',
    billingCycle: 'monthly',
    renewalDate: '2025-03-01',
    status: 'online',
    uptime: 99.95,
    lastCheck: '2025-02-09T10:00:00Z',
    cpuUsage: 45,
    ramUsage: 62,
    diskUsage: 38,
    tags: ['production', 'api', 'critical'],
    ownerId: 'user-3',
    ownerName: 'Mike Thompson',
    securityChecklist: {
      sshKeys: true,
      fail2ban: true,
      firewall: true,
      backups: true,
    },
    createdAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'srv-2',
    name: 'prod-web-01',
    provider: 'aws',
    region: 'us-east-1',
    environment: 'production',
    publicIp: '54.***.***.124',
    hostname: 'www.acme.com',
    os: 'Ubuntu 22.04 LTS',
    cpu: '2 vCPU',
    ram: '8 GB',
    disk: '50 GB SSD',
    sshPort: 22,
    firewallEnabled: true,
    monitoringEnabled: true,
    monthlyCost: 80,
    currency: 'USD',
    billingCycle: 'monthly',
    renewalDate: '2025-03-01',
    status: 'online',
    uptime: 99.99,
    lastCheck: '2025-02-09T10:00:00Z',
    cpuUsage: 25,
    ramUsage: 45,
    diskUsage: 22,
    tags: ['production', 'web'],
    ownerId: 'user-3',
    ownerName: 'Mike Thompson',
    securityChecklist: {
      sshKeys: true,
      fail2ban: true,
      firewall: true,
      backups: true,
    },
    createdAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'srv-3',
    name: 'staging-01',
    provider: 'digitalocean',
    region: 'nyc1',
    environment: 'staging',
    publicIp: '165.***.***.45',
    os: 'Ubuntu 22.04 LTS',
    cpu: '2 vCPU',
    ram: '4 GB',
    disk: '80 GB SSD',
    sshPort: 22,
    firewallEnabled: true,
    monitoringEnabled: true,
    monthlyCost: 24,
    currency: 'USD',
    billingCycle: 'monthly',
    renewalDate: '2025-03-01',
    status: 'online',
    uptime: 99.5,
    lastCheck: '2025-02-09T09:55:00Z',
    cpuUsage: 15,
    ramUsage: 35,
    diskUsage: 28,
    tags: ['staging', 'testing'],
    ownerId: 'user-3',
    ownerName: 'Mike Thompson',
    securityChecklist: {
      sshKeys: true,
      fail2ban: false,
      firewall: true,
      backups: false,
    },
    createdAt: '2024-08-01T00:00:00Z',
  },
];

// Demo Services
export const demoServices: ServiceApp[] = [
  {
    id: 'svc-1',
    name: 'API Gateway',
    serverId: 'srv-1',
    serverName: 'prod-api-01',
    domain: 'api.acme.com',
    status: 'running',
    deployMethod: 'docker',
    ports: ['443', '80'],
    repoUrl: 'https://github.com/acme/api',
    lastDeployAt: '2025-02-08T14:30:00Z',
    ownerId: 'user-3',
    ownerName: 'Mike Thompson',
    healthCheckUrl: 'https://api.acme.com/health',
    createdAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'svc-2',
    name: 'Frontend App',
    serverId: 'srv-2',
    serverName: 'prod-web-01',
    domain: 'www.acme.com',
    status: 'running',
    deployMethod: 'docker',
    ports: ['443', '80'],
    repoUrl: 'https://github.com/acme/frontend',
    lastDeployAt: '2025-02-09T08:00:00Z',
    ownerId: 'user-3',
    ownerName: 'Mike Thompson',
    healthCheckUrl: 'https://www.acme.com',
    createdAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'svc-3',
    name: 'PostgreSQL Database',
    serverId: 'srv-1',
    serverName: 'prod-api-01',
    status: 'running',
    deployMethod: 'docker',
    ports: ['5432'],
    ownerId: 'user-3',
    ownerName: 'Mike Thompson',
    createdAt: '2024-06-01T00:00:00Z',
  },
];

// Demo Incidents
export const demoIncidents: Incident[] = [
  {
    id: 'inc-1',
    title: 'API Gateway High Latency',
    severity: 'medium',
    affectedServers: ['srv-1'],
    affectedServices: ['svc-1'],
    status: 'resolved',
    impact: 'Increased response times for API requests',
    startTime: '2025-02-05T14:00:00Z',
    endTime: '2025-02-05T15:30:00Z',
    timeline: [
      { id: 'evt-1', timestamp: '2025-02-05T14:00:00Z', description: 'Alert triggered: API latency > 500ms', createdBy: 'System' },
      { id: 'evt-2', timestamp: '2025-02-05T14:15:00Z', description: 'Investigation started', createdBy: 'Mike Thompson' },
      { id: 'evt-3', timestamp: '2025-02-05T15:00:00Z', description: 'Root cause identified: Database connection pool exhaustion', createdBy: 'Mike Thompson' },
      { id: 'evt-4', timestamp: '2025-02-05T15:30:00Z', description: 'Resolved: Connection pool increased', createdBy: 'Mike Thompson' },
    ],
    resolution: 'Increased database connection pool size from 20 to 50',
    createdBy: 'System',
    createdAt: '2025-02-05T14:00:00Z',
  },
];

// Demo Maintenance Windows
export const demoMaintenanceWindows: MaintenanceWindow[] = [
  {
    id: 'maint-1',
    serverId: 'srv-1',
    serverName: 'prod-api-01',
    reason: 'Security patches and system updates',
    scheduledStart: '2025-02-15T02:00:00Z',
    scheduledEnd: '2025-02-15T04:00:00Z',
    status: 'scheduled',
    notifyTeams: ['Engineering', 'Support'],
    createdBy: 'Mike Thompson',
    createdAt: '2025-02-08T10:00:00Z',
  },
];

// Demo Projects
export const demoProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'Q1 Platform Upgrade',
    description: 'Major platform upgrade including new features and performance improvements',
    status: 'active',
    startDate: '2025-01-01',
    endDate: '2025-03-31',
    budget: 50000,
    spent: 18500,
    managerId: 'user-3',
    managerName: 'Mike Thompson',
    members: ['user-1', 'user-3'],
    createdAt: '2024-12-15T00:00:00Z',
  },
];

// Demo Tasks
export const demoTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Implement new authentication flow',
    description: 'Add OAuth2 support for third-party integrations',
    projectId: 'proj-1',
    projectName: 'Q1 Platform Upgrade',
    assigneeId: 'user-3',
    assigneeName: 'Mike Thompson',
    status: 'in_progress',
    priority: 'high',
    dueDate: '2025-02-20',
    createdAt: '2025-01-15T00:00:00Z',
  },
  {
    id: 'task-2',
    title: 'Database migration script',
    projectId: 'proj-1',
    projectName: 'Q1 Platform Upgrade',
    assigneeId: 'user-3',
    assigneeName: 'Mike Thompson',
    status: 'todo',
    priority: 'medium',
    dueDate: '2025-02-25',
    createdAt: '2025-02-01T00:00:00Z',
  },
];

// Demo Notifications
export const demoNotifications: Notification[] = [
  {
    id: 'notif-1',
    type: 'warning',
    module: 'expense',
    title: 'Budget Alert',
    message: 'Infrastructure budget is at 75% capacity',
    read: false,
    actionUrl: '/expenses/budgets',
    createdAt: '2025-02-09T08:00:00Z',
  },
  {
    id: 'notif-2',
    type: 'info',
    module: 'servers',
    title: 'Maintenance Scheduled',
    message: 'prod-api-01 maintenance window on Feb 15',
    read: false,
    actionUrl: '/servers/maintenance',
    createdAt: '2025-02-08T10:00:00Z',
  },
  {
    id: 'notif-3',
    type: 'success',
    module: 'erp',
    title: 'Invoice Paid',
    message: 'TechStart Inc. paid INV-2025-001',
    read: true,
    actionUrl: '/invoices/inv-1',
    createdAt: '2025-02-07T14:00:00Z',
  },
];

// Demo Audit Logs
export const demoAuditLogs: AuditLog[] = [
  {
    id: 'audit-1',
    userId: 'user-1',
    userName: 'Alex Johnson',
    action: 'create',
    module: 'invoices',
    entityType: 'Invoice',
    entityId: 'inv-3',
    createdAt: '2025-02-05T10:30:00Z',
  },
  {
    id: 'audit-2',
    userId: 'user-3',
    userName: 'Mike Thompson',
    action: 'update',
    module: 'servers',
    entityType: 'Server',
    entityId: 'srv-1',
    changes: { monitoringEnabled: { old: false, new: true } },
    createdAt: '2025-02-04T15:45:00Z',
  },
];

// Demo Accounts (Chart of Accounts)
export const demoAccounts: Account[] = [
  { id: 'acc-1', code: '1000', name: 'Cash', type: 'asset', balance: 125000 },
  { id: 'acc-2', code: '1100', name: 'Accounts Receivable', type: 'asset', balance: 77300 },
  { id: 'acc-3', code: '2000', name: 'Accounts Payable', type: 'liability', balance: 25000 },
  { id: 'acc-4', code: '4000', name: 'Sales Revenue', type: 'income', balance: 248500 },
  { id: 'acc-5', code: '5000', name: 'Operating Expenses', type: 'expense', balance: 85200 },
];

// Export function to get all demo data
export const getDemoData = () => ({
  organization: demoOrganization,
  users: demoUsers,
  customers: demoCustomers,
  leads: demoLeads,
  invoices: demoInvoices,
  products: demoProducts,
  warehouses: demoWarehouses,
  vendors: demoVendors,
  expenseCategories: demoExpenseCategories,
  expenses: demoExpenses,
  subscriptions: demoSubscriptions,
  budgets: demoBudgets,
  employees: demoEmployees,
  servers: demoServers,
  services: demoServices,
  incidents: demoIncidents,
  maintenanceWindows: demoMaintenanceWindows,
  projects: demoProjects,
  tasks: demoTasks,
  notifications: demoNotifications,
  auditLogs: demoAuditLogs,
  accounts: demoAccounts,
});
